language: node_js
cache: yarn
node_js:
  - "8"
  - "9"

script: yarn test

jobs:
  include:
    - stage: npm
      node_js: "8"
      if: tag =~ ^v\d.*
      deploy:
          provider: npm
          script: yarn build
          email: "jondotan@gmail.com"
          skip_cleanup: true
          api_key:
            secure: LxHsLVpAWutzsFAc0u5ZFCwSTlbRVkFOqBu6AmOYtbF2196CbdGjuhnoquELJgSDIIgIC/p7ZvZdckwL+cd0PrbFWnVr20sD5yxD/zzQQdHERwUAXPlCOsvxT0+vEgDshc7UqnwZ0C+SfJ6lExlqPMjzTuX/G//FUTVbzKMrOYNy6G78IWLoBF8q+7BkpzLGSSo1XEJIMc+CJgrrCUt9R0PG5EsBcchHo5Dp34zMSCnxn2GTNa/R60+6YVvC+y16BvJ88tMqQlCMLvJhitAfiWhtM4qMDunB3ftlpeb6MmbnWeWanlokhyArZalUabbT5LZCDm3kVKDWXhBlfgfnXlJZ3eAHpnX0TTjEysUARcEf2Lynxr0ulytO5EwOgHuLikTDtw0PjhlSxmY3AWzHhR+d1ThGWoTpP665BpRU9kNHeYW+fDaUdxzKHM+Lu6ELqxudl3G+HtzdG7hQugvbe4sV0nzcbj8Rhx//sYWsS9BSJ0d/HaQb1r9x0WwkmcvqJBRq1FseJjfAFGVKgS5dcb5mp/NPJ+C5xJPHD9TyHM229/3NoXFCuGNCcaym3p4jd5DXTwbISOsSBfX6OHrF74X89L5O6/rREVXMdnMEYMFTNt2vxt1XFzaSVAUJpt2JMUQgjlDCuMe5vaJnGp5aawKYIU4t2KU0mrOdcYs6miA=
          on:
            tags: true
#    - stage: docs
#      script: yarn docs:prepare && yarn docs:build
#      node_js: "8"
#      deploy:
#        provider: pages
#        local-dir: hygen.io/public
#        skip-cleanup: true
#        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#        keep-history: true
#    - stage: binary releases
#      script: yarn standalone
#      if: tag =~ ^v\d.*
#      node_js: "8"
#      deploy:
#        provider: releases
#        api_key: $GITHUB_TOKEN
#        file_glob: true
#        file: standalone/*
#        skip_cleanup: true
#        on:
#          tags: true
